spring.application.name=worker

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=company
spring.mongodb.username=admin
spring.mongodb.password=jmgsTest

url.client.api=http://localhost:8000/api/v1