FROM golang:1.26.1-alpine AS build

WORKDIR /go/src/app
COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o /go/bin/app

FROM gcr.io/distroless/static-debian12

ENV SERVER_ADDRESS=:8000
ENV GIN_MODE=release
ENV MONGODB_URI=""
ENV REDIS_URI=""

COPY --from=build /go/bin/app /
EXPOSE 8000

CMD ["/app"]